### ISSUE TITLE
Thank you very much for providing this tool

### ISSUE THREAD

**Issue by Liaojinghui** [nspcc-dev/neo-bench#110]
Hi @roman-khimov, just want to say thank you to you for developing this useful and powerful benchmark tool and thank you very much for the detailed document. It really helps.

**Comment by roman-khimov** [comment]
It's a team work and I'm even far from being the main contributor here:
https://github.com/nspcc-dev/neo-bench/graphs/contributors
But yeah, thanks!

We've made it because we needed it and it helped us a lot in understanding node's performance. I hope it can help any other node as well.
