### ISSUE TITLE
ERROR 137 while run `make start`

### ISSUE THREAD

**Issue by Jim8y** [nspcc-dev/neo-bench#111]
Hi, I encountered error while try to run Neo-bench with command `make start` after `make build`:

```bash
2021/11/16 21:45:25 #9: 42084 transactions in 5082 ms - 8280.991736 tps
2021/11/16 21:45:26 #10: 13974 transactions in 5443 ms - 2567.334191 tps
2021/11/16 21:45:32 CPU: 83.537%, Mem: 1281.168MB
2021/11/16 21:45:34 #11: 29091 transactions in 5826 ms - 4993.305870 tps
2021/11/16 21:45:38 #12: 24115 transactions in 5352 ms - 4505.792227 tps
ERROR: 137
=> Stop environment
./runner.sh -d "Go4x1" -m wrk -w 100 -z 5m -t 30s
=> Stop environment
=> Generate configurations for single-node and four-nodes networks from templates
+ cd ./cmd
+ go run ./config/ --go-template go.protocol.template.yml --go-db leveldb --sharp-template sharp.protocol.template.yml --sharp-db LevelDBStore
creating: 3673
```

This error did not stop the benchmark, and I am not sure whether this matters.

**Comment by roman-khimov** [comment]
That's interesting. Never seen anything like that before. Looks like the only case where this might get printed is when missing transaction dumps. `make gen` (although it should be done automatically due to `make` dependencies)?

**Comment by Liaojinghui** [comment]
Hi @roman-khimov, the previous error does not stop the go benchmark. But now I run into a new error while trying to run the CSharp benchmark, and this stops the benchmark:

```bash
ERROR: for healthy  Container "f919d959a93c" is unhealthy.
ERROR: Encountered errors while bringing up the project.
=> Stop environment
./runner.sh --validators 1 --nodes sharp -d "SharpSingle" -m wrk -w 30 -z 5m -t 30s
=> Stop environment
=> Generate configurations for single-node and four-nodes networks from templates
+ cd ./cmd
+ go run ./config/ --go-template go.protocol.template.yml --go-db leveldb --sharp-template sharp.protocol.template.yml --sharp-db LevelDBStore
creating: 3802775804/go.protocol.template.yml
creating: 3802775804/go.protocol.template.yml
creating: 3802775804/sharp.protocol.template.yml
creating: 3802775804/sharp.protocol.template.yml
Creating network "neo_go_network" with the default driver
Creating ir_node_1 ... done
```
I just run the benchmark with the default setting from this repo, can you help me with this? thank you

**Comment by roman-khimov** [comment]
What's the OS you're using? Did you use `-j` flag? Have you tried `make start.SharpSingle10wrk` to run single test? Unhealthy container means the (containerized) node doesn't work correctly. As of today we have 3.0.3 C# node and it works fine, I'm pretty sure the container image built should be fine. So it's likely to be OS/firewall/something like that.

**Comment by roman-khimov** [comment]
Obsolete, can't be reproduced.
