### ISSUE TITLE
Store Bench testing reports into NeoFS

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-bench#145]
We have NeoGo, NeoSharp and Mixed test benchmarks running at every PR since #142. The benchmark results (TPS, TPB, etc.) are not published to anywhere, and I'd suggest to publish them to NeoFS testnet.

These results are not very demonstrative, because we use GitHub runners for benchmark runs, and every time the hardware constraints are different. However, this issue may be treated as an attempt to bring more life to NeoFS testnet and maybe one day we'll have a dedicated self-hosted runner to run our benchmarks on it, then we can compare TPS values between different PRs.

**Comment by roman-khimov** [comment]
Not planned.
