### ISSUE TITLE
Drop make usage for test runs

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-bench#4]
It may be useful for builds (but that is not obvious for this particular case), but uncommenting something to run the test is just plain wrong, we need some trivial `./run.sh -with -some -flags` to drive test execution.

**Comment by roman-khimov** [comment]
Another possibility of course is to make it more usable with different targets for different runs and proper dependencies.

**Comment by fyrchik** [comment]
Also related #86
