### ISSUE TITLE
Add ability to add delays/losses to the network

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-bench#85]
It's rather simple to run `tc` inside a container to simulate a little less perfect network than Docker usually has. It at the same time is important to at least try to understand how things work in a more real environment. Related to nspcc-dev/neo-go#1770.

**Comment by roman-khimov** [comment]
200ms delays and 0.1-0.5% packet loss are the most interesting, but some less realistic though tougher environments are interesting too.

**Comment by fyrchik** [comment]
Fixed via #86 .
